// example of custom API
import groovy.json.JsonSlurperClassic 

@NonCPS
def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

// def repo = "edwardviaene/jenkins-course"

// def token = httpRequest authentication: 'bitbucket-oauth', contentType: 'APPLICATION_FORM', httpMode: 'POST', requestBody: 'grant_type=client_credentials', url: 'https://bitbucket.org/site/oauth2/access_token'
// def accessToken = jsonParse(token.content).access_token
// def pr = httpRequest customHeaders: [[maskValue: true, name: 'Authorization', value: 'Bearer ' + accessToken]], url: "https://api.bitbucket.org/2.0/repositories/${repo}/pullrequests"
def pr = httpRequest url: "http://api.exchangeratesapi.io/v1/latest?access_key=ca05b43b2ac172d7ddb851923c5f3d1c"

for (p in jsonParse(pr.content).values) { 
    println(p.rates.HKD)
}
