node {
  stage('do something with git') {  
    sshagent (credentials: ['github-testkey']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs git@github.com:oyip1211/jenkins-course.git master |awk "{print $1}"'
    }
  }
}
